package application

import (
	"bll"
	"bll/common"
	"dal"
	"flag"
	"log"
	"os"
	"util"
)

const taskCalculate = "calculate"
const taskCompare = "compare"
const taskExport = "export"
const taskImport = "import"
const taskVerify = "verify"

// Application Contains main application logic.
type Application struct {
	config  configuration
	logFile *os.File
}

type configuration struct {
	task            string
	algorithm       string
	inputChecksum   string
	inputDirectory  string
	outputChecksum  string
	outputDirectory string
	outputNames     string
	basePath        string
	filter          string
	missingOnly     bool
	logPath         string
}

// Initialize Initializes the application.
func (app *Application) Initialize() {

	defaultConfig := configuration{taskCalculate, dal.SHA1, "", "", "", "", "", "", "", false, ""}
	app.parseCommandLineArguments(defaultConfig)
	app.verifyConfiguration()
}

// Execute Executes the application.
func (app *Application) Execute() {

	app.initializeLog()
	defer app.cleanUp()

	conf := app.config
	db := dal.NewCsvDatabase(conf.inputChecksum, conf.outputChecksum, conf.outputNames)

	if app.config.task == taskCalculate {
		calculator := bll.NewCalculator(db, conf.inputDirectory, conf.algorithm, conf.basePath)
		calculator.Calculate(conf.missingOnly)
	} else if app.config.task == taskCompare {
		comparer := bll.NewComparer(db, conf.inputDirectory, app.config.basePath)
		comparer.Compare(app.config.algorithm)
	} else if app.config.task == taskExport {
		exporter := bll.NewExporter(db, conf.outputDirectory, conf.basePath)
		fpFilter := common.NewFingerprintFilter(conf.filter)
		exporter.Convert(fpFilter)
	} else if app.config.task == taskImport {
		importer := bll.NewImporter(db, conf.inputDirectory, conf.outputChecksum)
		importer.Convert()
	} else if app.config.task == taskVerify {
		verifier := bll.NewVerifier(db, conf.basePath)
		fpFilter := common.NewFingerprintFilter(conf.filter)
		verifier.Verify(conf.missingOnly, fpFilter)
	}
}

func (app *Application) parseCommandLineArguments(defaultConfig configuration) {

	algorithm := flag.String("alg", defaultConfig.algorithm, "The algorithm used to calculate new checksums.")
	basePath := flag.String(
		"bp",
		defaultConfig.basePath,
		"The first part of the path that will not be stored in the output.")
	filter := flag.String(
		"filter",
		defaultConfig.filter,
		"A string in \"filename:algorithm\" format that exported or verified filenames/algorithms must match. Both"+
			"parts are optional.")
	inputChecksum := flag.String(
		"inchk",
		defaultConfig.inputChecksum,
		"The name of the input CSV containing checksums.")
	inputDirectory := flag.String(
		"indir",
		defaultConfig.inputDirectory,
		"The source directory for which the checksums will be calculated (or will be compared). Or the directory"+
			" containing the files to import.")
	logPath := flag.String(
		"log",
		defaultConfig.logPath,
		"Path of the log file. Optional, by default the program will print log messages to the standard error output.")
	outputChecksum := flag.String(
		"outchk",
		defaultConfig.outputChecksum,
		"The name of the output CSV file containing checksums.")
	outputDirectory := flag.String(
		"outdir",
		defaultConfig.outputDirectory,
		"The name of the directory containing exported files.")
	outputNames := flag.String(
		"outnames",
		defaultConfig.outputNames,
		"The name of the output containing new file name and old filename pairs.")
	task := flag.String(
		"task",
		defaultConfig.task,
		"The task to execute: calculate, compare, import, export or verify. The first one calculates checksums for a"+
			" directory and stores the results in a CSV. The second compares stored checksums with the checksums of"+
			" the files in the given directory and stores filename matches. The third imports checksums from files"+
			" generated by Linux utilities or Total Commander. The fourth exports to Total Commander's formats. The"+
			" fifth verifies checksums for the files listed in the given CSV.")
	missingOnly := flag.Bool(
		"missingonly",
		defaultConfig.missingOnly,
		"For calculate task it means that calculation is requested for those files only that do not have a checksum"+
			" stored yet. In case of the verify task, set it to true if you would like to verify only if each file"+
			" exists.")

	flag.Parse()

	app.config = configuration{
		*task, *algorithm,
		*inputChecksum, *inputDirectory,
		*outputChecksum, *outputDirectory, *outputNames,
		*basePath, *filter, *missingOnly, *logPath}
}

func (app *Application) verifyConfiguration() {

	if app.config.task == taskCalculate {
		app.stopIfInputDirectoryDoesNotExist()
		if app.config.missingOnly {
			app.stopIfInputChecksumDoesNotExist()
		} else {
			app.config.inputChecksum = ""
		}
	} else if app.config.task == taskCompare {
		app.stopIfInputChecksumDoesNotExist()
		app.stopIfInputDirectoryDoesNotExist()
	} else if app.config.task == taskExport {
		app.stopIfOutputDirectoryDoesNotExist()
	} else if app.config.task == taskImport {
		app.stopIfInputDirectoryDoesNotExist()
	} else if app.config.task == taskVerify {
		app.stopIfInputChecksumDoesNotExist()
	} else {
		log.Fatalln("Unknown task.")
	}
}

func (app *Application) initializeLog() {

	if app.config.logPath == "" {
		return
	}

	file, err := os.OpenFile(app.config.logPath, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		app.logFile = nil
	}

	app.logFile = file
	log.SetOutput(app.logFile)
}

func (app *Application) cleanUp() {

	if app.logFile != nil {
		app.logFile.Close()
	}
}

func (app *Application) stopIfInputChecksumDoesNotExist() {

	if app.config.inputChecksum == "" || !util.CheckIfFileExists(app.config.inputChecksum) {
		log.Fatalln("Input file does not exist.")
	}
}

func (app *Application) stopIfInputDirectoryDoesNotExist() {

	if app.config.inputDirectory == "" || !util.CheckIfDirectoryExists(app.config.inputDirectory) {
		log.Fatalln("Directory " + app.config.inputDirectory + " does not exist.")
	}
}

func (app *Application) stopIfOutputDirectoryDoesNotExist() {

	if !util.CheckIfDirectoryExists(app.config.outputDirectory) {
		log.Fatalln("Directory " + app.config.outputDirectory + " does not exist.")
	}
}
